repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.12.10
    hooks:
      - id: ruff
        args: ["--fix"]
      - id: ruff-format

  - repo: https://github.com/psf/black
    rev: 25.1.0
    hooks:
      - id: black

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: check-added-large-files
      - id: check-merge-conflict
      - id: end-of-file-fixer
      - id: trailing-whitespace

  - repo: local
    hooks:
      - id: fe-eslint
        name: Frontend ESLint
        language: system
        pass_filenames: true
        files: ^frontend/.*\.(ts|tsx|js|jsx)$
        entry: bash -lc 'cd frontend && pnpm eslint --max-warnings 0 "../$@"'
  # --- Frontend: Prettier (format) ---
  - repo: local
    hooks:
      - id: fe-prettier
        name: Frontend Prettier
        language: system
        pass_filenames: true
        files: ^frontend/.*\.(ts|tsx|js|jsx|json|css|scss|md|html|yml|yaml)$
        entry: bash -lc 'cd frontend && pnpm prettier --write "../$@"'
