services:
  db:
    image: postgres:16
    env_file:
      - .env.prod
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB" ]
      interval: 5s
      timeout: 5s
      retries: 10
    volumes:
      - pgdata:/var/lib/postgresql/data

  backend:
    build:
      context: ../backend
      target: prod
    env_file:
      - .env.prod
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - staticfiles:/static

  nginx:
    build:
      context: ./nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/certs:/etc/nginx/certs:ro
      - ./nginx/default.prod.conf:/etc/nginx/conf.d/default.conf:ro
      - staticfiles:/static:ro
    depends_on:
      - backend

volumes:
  pgdata:
  staticfiles:
