x-env-common: &env_common
  DJANGO_DEBUG: "True"
  DJANGO_ALLOWED_HOSTS: "*"
  DJANGO_SECRET_KEY: dev-only-change-me

services:
  backend:
    build:
      context: ../backend
      target: dev
    environment:
      <<: *env_common
    volumes:
      - ../backend:/app
      - ..:/workspace:ro
      - /app/.venv
    working_dir: /app/src
    command: ["python", "-m", "app.manage", "runserver", "0.0.0.0:8000"]
    ports:
      - "8000:8000" # direct access (useful for debugging)
  frontend:
    image: node:20
    working_dir: /app
    command: sh -lc "corepack enable && pnpm install --frozen-lockfile && pnpm dev --host 0.0.0.0"
    ports:
      - "5173:5173" # optional (useful to visit Vite directly)
    volumes:
      - ../frontend:/app:cached
      - /app/node_modules
      - ../:/workspace:ro
    environment:
      # Vite defaults; no /api prefix change needed since nginx proxies /api → backend
      NODE_ENV: development
      CI: "true" # ← avoid any interactive prompts
      VITE_PROXY_TARGET: http://backend:8000
    depends_on:
      - backend
  nginx:
    build:
      context: ..
      dockerfile: deploy/nginx/Dockerfile
    ports:
      - "8080:80" # stable entrypoint for CI/staging-like flows
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - backend
