name: CI

on:
  push:
    branches: ["**"]
  pull_request:
    branches: ["**"]

jobs:
  backend:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Compose up (detached) via Make
        run: make up

      - name: Wait for backend
        run: make be.wait

      - name: Verify (inside container) via Make
        run: make be.ci fe.ci

      - name: Smoke test via Nginx
        run: make smoke

      - name: Tear down
        if: always()
        run: make down
